### ISSUE TITLE
Support for Shelly EM

### ISSUE THREAD

**Issue by robao23** [mario-peters/ShellyCloudPlugin#1]
Hi

Fed up with the problems with shelly in domoticz with mqtt I have come across this.

It's amazing!

Would it be possible to add support to Shelly EM?

Regards.

**Comment by robao23** [comment]
I am investigating the data that EM collects.

ip/settings

{
  "device": {
    "type": "SHEM",

...


`  "emeters": [
    {
      "power": 2465.01,
      "reactive": -750.87,
      "voltage": 238.78,
      "is_valid": true,
      "total": 558473.7,
      "total_returned": 22466.3
    },
    {
      "power": 0,
      "reactive": 0,
      "voltage": 238.78,
      "is_valid": true,
      "total": 25227.5,
      "total_returned": 4303.7
    }
  ],`

All info:

`{
  "device": {
    "type": "SHEM",
    "mac": "XXXXXXXX",
    "hostname": "shellyem-XXXXXX",
    "num_outputs": 1,
    "num_meters": 0,
    "num_emeters": 2,
    "report_period": 1
  },
  "wifi_ap": {
    "enabled": false,
    "ssid": "shellyem-XXXXXX",
    "key": ""
  },
  "wifi_sta": {
    "enabled": true,
    "ssid": "XXXX",
    "ipv4_method": "dhcp",
    "ip": null,
    "gw": null,
    "mask": null,
    "dns": null
  },
  "wifi_sta1": {
    "enabled": false,
    "ssid": null,
    "ipv4_method": "dhcp",
    "ip": null,
    "gw": null,
    "mask": null,
    "dns": null
  },
  "mqtt": {
    "enable": true,
    "server": "192.168.X.XX:1883",
    "user": "",
    "id": "shellyem-XXXXXX",
    "reconnect_timeout_max": 60,
    "reconnect_timeout_min": 2,
    "clean_session": true,
    "keep_alive": 60,
    "max_qos": 0,
    "retain": false,
    "update_period": 30
  },
  "coiot": {
    "update_period": 15
  },
  "sntp": {
    "server": "time.google.com",
    "enabled": true
  },
  "login": {
    "enabled": false,
    "unprotected": false,
    "username": "admin"
  },
  "pin_code": "D)B)n!",
  "name": null,
  "fw": "20201124-092817/v1.9.0@57ac4ad8",
  "discoverable": false,
  "build_info": {
    "build_id": "20201124-092817/v1.9.0@57ac4ad8",
    "build_timestamp": "2020-11-24T09:28:17Z",
    "build_version": "1.0"
  },
  "cloud": {
    "enabled": false,
    "connected": false
  },
  "timezone": "Europe/Madrid",
  "lat": 49.99999,
  "lng": 332.3334,
  "tzautodetect": true,
  "tz_utc_offset": 3600,
  "tz_dst": false,
  "tz_dst_auto": true,
  "time": "10:08",
  "unixtime": 1608199693,
  "led_status_disable": false,
  "actions": {
    "active": false,
    "names": [
      "over_power_url",
      "under_power_url",
      "over_power_url",
      "under_power_url",
      "out_on_url",
      "out_off_url"
    ]
  },
  "hwinfo": {
    "hw_revision": "prod-191230",
    "batch_id": 1
  },
  "relays": [
    {
      "name": null,
      "ison": false,
      "has_timer": false,
      "default_state": "off",
      "auto_on": 0,
      "auto_off": 0,
      "schedule": false,
      "schedule_rules": []
    }
  ],
  "emeters": [
    {
      "name": null,
      "appliance_type": "General",
      "ctraf_type": 50,
      "max_power": 0
    },
    {
      "name": null,
      "appliance_type": "General",
      "ctraf_type": 50,
      "max_power": 0
    }
  ]
}
`

**Comment by mario-peters** [comment]
Functionality added in current version
