### ISSUE TITLE
Wrong energy calculation for EM and 3EM

### ISSUE THREAD

**Issue by BosseSax** [mario-peters/ShellyCloudPlugin#11]
Since the energy data sent from EM/3EM differs from other Shelly energy meters the enrgy calculation will be wrong. 

EM/3EM sends energy count in "Watt-hours" instead of the others which sends in "Watt-minutes" there will be a factor 60 wrong. 

Ie for EM/3EM there should not be a calculation of energy divided with 60 but use the data as it is.

Suggestion: 
            total=int(value/60)
            if Parameters["Mode1"] == "SHEM" or Parameters["Mode1"] == "SHEM-3":
                total=int(value)

**Comment by mario-peters** [comment]
fixed
