### ISSUE TITLE
Support for Shelly Gas

### ISSUE THREAD

**Issue by pizzulicchio** [mario-peters/ShellyCloudPlugin#3]
Hi,
i have bought a Shelly Gas but this product seems to not be supported from your plugin.
https://shelly-api-docs.shelly.cloud/#shelly-gas

What do you need for implementing it?
This is something of util.

The domoticz log of device:

MQTT message: shellies/shellygas-10521CF29E18/sensor/operation normal
MQTT message: shellies/shellygas-10521CF29E18/sensor/gas none
MQTT message: shellies/shellygas-10521CF29E18/sensor/self_test not_completed
MQTT message: shellies/shellygas-10521CF29E18/valve/0/state not_connected
MQTT message: shellies/shellygas-10521CF29E18/sensor/concentration 0

the log of mosquitto

1611744512: Received PUBLISH from shellygas-10521CF29E18 (d0, q0, r0, m0, 'shellies/shellygas-10521CF29E18/sensor/operation', ... (6 bytes))
1611744512: Received PUBLISH from shellygas-10521CF29E18 (d0, q0, r0, m0, 'shellies/shellygas-10521CF29E18/sensor/gas', ... (4 bytes))
1611744512: Received PUBLISH from shellygas-10521CF29E18 (d0, q0, r0, m0, 'shellies/shellygas-10521CF29E18/sensor/self_test', ... (13 bytes))
1611744512: Received PUBLISH from shellygas-10521CF29E18 (d0, q0, r0, m0, 'shellies/shellygas-10521CF29E18/valve/0/state', ... (13 bytes))
1611744512: Received PUBLISH from shellygas-10521CF29E18 (d0, q0, r0, m0, 'shellies/shellygas-10521CF29E18/sensor/concentration', ... (1 bytes))

**Comment by mario-peters** [comment]
fixed in new version
