### ISSUE TITLE
Roller Functionality Positioning feature Not Working

### ISSUE THREAD

**Issue by mdal21** [mario-peters/ShellyCloudPlugin#4]
Just tested the ShellyCloudPlugin with my Shelly2.5. I have to report that although Open/Close work but the positioning feature is not working at all (no response).  I have tested against direct HTTP requests that work as expected.

**Comment by mdal21** [comment]
Issue found. Is a typo in the python plugin.

Line 126 should be "url = url + "?go=to_pos&roller_pos="+str(Level)". An underscore was missing from "to_pos".

**Comment by mario-peters** [comment]
fixed
