### ISSUE TITLE
Support 3EM

### ISSUE THREAD

**Issue by Cino2424** [mario-peters/ShellyCloudPlugin#5]
Settings:
{"device":{"type":"SHEM-3","mac":"8CAAB561D496","hostname":"shellyem3-8CAAB561D496","num_outputs":1,"num_meters":0,"num_emeters":3,"report_period":1},"wifi_ap":{"enabled":false,"ssid":"shellyem3-8CAAB561D496","key":""},"wifi_sta":{"enabled":true,"ssid":"","ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},"wifi_sta1":{"enabled":false,"ssid":null,"ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},"ap_roaming":{"enabled":false,"threshold":-70},"mqtt": {"enable":false,"server":"192.168.33.3:1883","user":"","id":"shellyem3-8CAAB561D496","reconnect_timeout_max":60.000000,"reconnect_timeout_min":2.000000,"clean_session":true,"keep_alive":60,"max_qos":0,"retain":false,"update_period":30},"coiot": {"enabled":false,"update_period":15,"peer":""},"sntp":{"server":"time.google.com","enabled":true},"login":{"enabled":false,"unprotected":false,"username":"admin"},"pin_code":"OPSoqf","name":"Zuleitung HAK","fw":"20210413-154243/v1.10.2-gb89901a","discoverable":false,"build_info":{"build_id":"20210413-154243/v1.10.2-gb89901a","build_timestamp":"2021-04-13T15:42:43Z","build_version":"1.0"},"cloud":{"enabled":true,"connected":true},"timezone":"Europe/Berlin","lat":50.937931,"lng":6.878530,"tzautodetect":true,"tz_utc_offset":7200,"tz_dst":true,"tz_dst_auto":true,"time":"15:19","unixtime":1618665581,"led_status_disable":false,"debug_enable":false,"allow_cross_origin":false,"actions":{"active":false,"names":["out_on_url","out_off_url","over_power_url","under_power_url","over_power_url","under_power_url","over_power_url","under_power_url","over_power_url","under_power_url"]},"hwinfo":{"hw_revision":"prod-2020-1", "batch_id":1},"relays":[{"name":null,"ison":false,"has_timer":false,"default_state":"off","auto_on":0.00,"auto_off":0.00,"schedule":false,"schedule_rules":[]}],"emeters":[{"name":"L1","appliance_type":"General","max_power":0},{"name":"L2","appliance_type":"General","max_power":0},{"name":"L3","appliance_type":"General","max_power":0}],"wifirecovery_reboot_enabled":true}

Status:
{"wifi_sta":{"connected":true,"ssid":"","ip":"192.168.0.60","rssi":-40},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":false},"time":"15:20","unixtime":1618665605,"serial":1380,"has_update":false,"mac":"8CAAB561D496","cfg_changed_cnt":13,"actions_stats":{"skipped":0},"relays":[{"ison":false,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"overpower":false,"is_valid":true,"source":"input"}],"emeters":[{"power":156.54,"pf":0.62,"current":1.09,"voltage":231.45,"is_valid":true,"total":98.7,"total_returned":0.0},{"power":260.72,"pf":0.75,"current":1.50,"voltage":231.66,"is_valid":true,"total":141.5,"total_returned":0.0},{"power":22.46,"pf":0.60,"current":0.16,"voltage":231.24,"is_valid":true,"total":22.9,"total_returned":0.0}],"fs_mounted":true,"update":{"status":"idle","has_update":false,"new_version":"20210413-154243/v1.10.2-gb89901a","old_version":"20210413-154243/v1.10.2-gb89901a"},"ram_total":48784,"ram_free":30084,"fs_size":233681,"fs_free":156122,"uptime":6613}

**Comment by mario-peters** [comment]
functionality added in last commit
